module.exports = {
  port: 3000,
  events: [
    "Admeta: Category 1", "Admeta: Category 2",
    "Artem",
    "Carmen: Category 1","Carmen: Category 2",
    "Fabula",
    "Fortuna",
    "Codeferno",
    "Gustatio",
    "Mahim 16",
    "'Ad'venturium",
    "Gratia",
    "Panache",
    "Symphonia",
    "Mr. and Mrs. Perseverantia",
    "Explorare",
    "Monopolium",
    "Football: U17 Boys","Football: U19 Boys","Football: U19 Girls",
    "Basketball: U19 Girls","Basketball: U19 Boys",
    "Gully Cricket",
    "Table Tennis",
    "Tug of War: U16 Boys","Tug of War: U16 Girls","Tug of War: U19 Boys","Tug of War: U19 Girls",
    "E-Sports"
  ],
  schools: [
    "P1",
    "P2",
    "P3",
    "P4",
    "P5",
    "P6",
    "P7",
    "P8",
    "P9",
    "P10",
    "P11",
    "P12",
    "P13",
    "P14",
    "P15",
    "P16",
    "P17",
    "P18",
    "P20",
    "P21",
    "P22",
    "P23",
    "P24",
    "P25",
    "P26",
    "P28",
    "P29",
  ]
};
